title:            高策
description:      好好学习，天天向上
logo:             logo.png
background:       
comments_sys:     duoshuo
disqus_shortname: blogofcece
share:            true
highlight:        true
dropcap:          true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''

# Owner/author information
owner:
  name:           高策
  avatar:         gaocegege.jpg
  email:          gaocegege@hotmail.com
  wechat:         270863799
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Done is better than perfect.
  # Social networking links used in footer. Update and remove as you like.
  renren:         325460067
  weibo:          constructcece
  twitter:        
  facebook:       gaocegege
  github:         gaocegege      
  instagram:      
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/109707369864071328013

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-54253120-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: 主页
    url: /
    external: false
    icon: home
  - title: 脱水区
    url: /featured
  - title: 水区
    url: /relaxed
  - title: 分类
    url: /categories
  - title: 关于我
    url: /about
  - title: 统计
    url: /analytics
  - title: Link
    url: /link
  - title: RSS
    url: /rss.xml

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Dili
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    10
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://gaocegege.com/Blog'
  relativeLinks: 'http://gaocegege.com/Blog/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
